# Generated by Django 4.0.6 on 2022-07-13 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_calendar_meal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='meal',
        ),
    ]
